FROM continuumio/miniconda3:latest

RUN conda install plotly=4.12.0 pandas=1.1.3 numpy=1.19.1 jupyterlab=2.2.6 ipywidgets=7.5.1 ipython=7.18.1 widgetsnbextension=3.5.1 qgrid=1.3.1 pyodbc=4.0.30 beautifulsoup4=4.9.3 lxml=4.6.1 openpyxl pytables fsspec pyyaml html5lib && \
    conda clean --all -f -y 

RUN conda install openpyxl pytables fsspec pyyaml html5lib && conda clean --all -f -y

RUN conda install -c conda-forge/label/gcc7 nodejs && conda clean --all -f -y

RUN conda install -c conda-forge elasticsearch pymysql=0.10.1 pyarrow ipysheet tabulate && conda clean --all -f -y

RUN pip install --quiet --no-cache-dir stix2 taxii2-client splunk-sdk==1.6.13 pandas-profiling yahoo_fin

RUN jupyter labextension install --dev-build=True @jupyter-widgets/jupyterlab-manager@2.0.0 && jupyter labextension install --dev-build=True plotlywidget@4.12.0 && \
    jupyter labextension install --dev-build=True jupyterlab-plotly@4.12.0 && jupyter labextension install --dev-build=True qgrid2@1.1.3 && \
    jupyter labextension install --dev-build=True ipysheet &&  conda clean --all -f -y && npm cache clean --force

