# Using a psfpython base image

FROM python:3.9.6-buster

ENV JIVERSION=psf_1.0.5

COPY requirements.txt /root
# COPY startup_files.sh /root


RUN apt-get update \
 && apt-get install --reinstall build-essential -y \
 && apt-get install unixodbc -y \
 && apt-get install unixodbc-dev -y \
 && apt-get install freetds-dev -y \
 && apt-get install freetds-bin -y \
 && apt-get install tdsodbc -y \
 && apt-get install --reinstall build-essential -y \
 && apt-get install tesseract-ocr -y \
 && apt-get autoremove -y \
 && apt-get install ffmpeg libsm6 libxext6 -y \
 && apt-get install gnutls-bin -y \
 && apt-get clean \
 && rm -rf /var/lib/apt/lists/*

RUN echo "[FreeTDS]\n\
Description = FreeTDS unixODBC Driver\n\
Driver = /usr/lib/x86_64-linux-gnu/odbc/libtdsodbc.so\n\
Setup = /usr/lib/x86_64-linux-gnu/odbc/libtdsS.so" >> /etc/odbcinst.ini
RUN echo "hi2"


RUN pip install --use-deprecated=legacy-resolver -r /root/requirements.txt

RUN pip install --trusted-host pypi.python.org pyodbc==4.0.30

# Everthing here should be all good and the same as the conda one



